// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsv1Jx-3Wr0SjiC29I2J8FYhimtl-jDi8',
    appId: '1:471954721185:web:e99845257677bc1c80e3e0',
    messagingSenderId: '36552390444',
    projectId: 'wagl-a8aad',
    authDomain: 'wagl-a8aad.firebaseapp.com',
    storageBucket: 'wagl-a8aad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEG9FRt6A8BxsJ3XHVDWH2pA6McBkYnQo',
    appId: '1:36552390444:android:e0f7e4a9bc401b06a1de89',
    messagingSenderId: '36552390444',
    projectId: 'wagl-a8aad',
    storageBucket: 'wagl-a8aad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtwE4yCbphdSGzsM_R_tRUHezvOEmiBwE',
    appId: '1:36552390444:ios:6e6a9c3bc858f1d0a1de89',
    messagingSenderId: '36552390444',
    projectId: 'wagl-a8aad',
    storageBucket: 'wagl-a8aad.firebasestorage.app',
    androidClientId: '36552390444-qrqp861i512a1r0o7l880kr91eej2c9o.apps.googleusercontent.com',
    iosClientId: '36552390444-sg80t6fanatpevq0mmuecu7a5ve9gdks.apps.googleusercontent.com',
    iosBundleId: 'com.wagl.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEG9FRt6A8BxsJ3XHVDWH2pA6McBkYnQo',
    appId: '1:471954721185:ios:d236219dce87b1f580e3e0',
    messagingSenderId: '36552390444',
    projectId: 'wagl-a8aad',
    storageBucket: 'wagl-a8aad.appspot.com',
    androidClientId: '471954721185-po5uuoqnir0auubbdodlp8qtcr292650.apps.googleusercontent.com',
    iosClientId: '471954721185-ubsdbop403vn08eh1hqp5sclkqhoiif0.apps.googleusercontent.com',
    iosBundleId: 'com.wagl.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEG9FRt6A8BxsJ3XHVDWH2pA6McBkYnQo',
    appId: '1:471954721185:web:c72cf517a4fd4ed480e3e0',
    messagingSenderId: '36552390444',
    projectId: 'wagl-a8aad',
    authDomain: 'wagl-a8aad.firebaseapp.com',
    storageBucket: 'wagl-a8aad.appspot.com',
  );
}