name: wagl
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.18.1
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  story_view: ^0.16.0
  google_places_flutter: ^2.0.6
  google_sign_in: ^6.1.5
  share_plus: ^7.2.2
  firebase_auth: ^4.0.0
  geolocator: ^9.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.3
  flutter_native_splash: ^2.3.7
  flutter_facebook_auth: ^7.0.0
  datepicker_dropdown: ^0.1.1+1
  dotted_border: ^2.1.0
  another_flushbar: ^1.12.30
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  path_provider: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  vs_story_designer: ^2.0.1
  media_picker_widget: ^1.0.3
#  image_picker_plus: ^0.5.9
  permission_handler: ^11.0.1
  video_player: ^2.8.5
  video_trimmer: ^3.0.1
  video_editor: ^3.0.0
  fraction: ^5.0.2
  flutter_contacts: ^1.1.9+2
  flutter_local_notifications: ^17.2.3
  hive: ^2.2.3
  firebase_core: ^2.24.1
  firebase_messaging: ^14.7.10
  hive_flutter: ^1.1.0
  firebase_analytics: 10.8.0
  image: ^4.2.0
  video_thumbnail: ^0.5.3
  dio: ^5.7.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about      deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" # flutter pub run flutter_launcher_icons:main


flutter_native_splash:
  android: true
  ios: true
  #color: '#FFCC00'
  background_image: assets/background/splash_screen.png #flutter pub run flutter_native_splash:create
#  image: assets/background/splash_screen.png #flutter pub run flutter_native_splash:create

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/design1.png
     - assets/images/onbroading_bg.png
     - assets/images/hexa_black.png
     - assets/images/background_web.png
     - assets/images/wagl_logo.png
     - assets/images/0.png
     - assets/images/1.png
     - assets/images/2.png
     - assets/images/3.png
     - assets/images/4.png
     - assets/images/5.png
     - assets/images/profile_img.png
     - assets/images/cust_dialog_img.png
     - assets/images/no_profile.png
     - assets/images/main_profile.png
     - assets/images/profile_field.png
     - assets/images/profile_field1.png
     - assets/images/profile_field2.png
     - assets/images/screenShot.png


     - assets/icons/food_icon.svg
     - assets/icons/discover_icon.svg
     - assets/icons/notification_icon.svg
     - assets/icons/home_icon.svg
     - assets/icons/wagl_icon.svg
     - assets/icons/settings_icon.svg
     - assets/icons/close_svg.svg
     - assets/icons/delete_icon.svg
     - assets/icons/add_icon.svg
     - assets/icons/triple_dot.svg
     - assets/icons/create_post_icon.svg
     - assets/icons/hezagoan_filled.svg
     - assets/icons/camera_svg.svg
     - assets/icons/gallery_svg.svg
     - assets/icons/right_arrow.svg
     - assets/icons/back_icon.svg
     - assets/icons/saved_wagl_svg.svg
     - assets/icons/temp.svg
     - assets/icons/left_arrow.svg
     - assets/icons/leaf_icon.svg
     - assets/icons/eye_icon.svg
     - assets/icons/like_icon.svg
     - assets/icons/dot_icon.svg
     - assets/icons/no_thumbnail.svg
     - assets/icons/cust_dialog.svg
     - assets/icons/video_image.png
     - assets/icons/multiple_image.png
     - assets/icons/hexagon_border.png
     - assets/icons/sent_icon_svg.svg
     - assets/icons/upload_icon.svg
     - assets/icons/cust_dialog.svg
     - assets/icons/no_image_svg.svg


     - assets/background/login_bg1.png
     - assets/background/login_bg2.png
     - assets/background/dailog_bg.png
     - assets/background/splash_screen.png



     - assets/icons/facebook_icon.png
     - assets/icons/no_image.png
     - assets/icons/google_icon.png
     - assets/icons/apple_icon.png
     - assets/icons/enter_icon.png
     - assets/icons/exit_icon.png
     - assets/icons/register_icon.png
     - assets/icons/failed_1.png
     - assets/icons/app_icon.png
     - assets/icons/add_post.png
     - assets/icons/flag_icon.png
     - assets/icons/notification_icon.png
     - assets/icons/discover_icon.png
     - assets/icons/home_icon.png
     - assets/icons/product_icon.png
     - assets/icons/like_icon.png
     - assets/icons/unlike_icon.png
     - assets/icons/search_icon.png
     - assets/icons/comment_icon.png
     - assets/icons/delete_icon_white.png
     - assets/icons/edit_icon.png
     - assets/icons/saved_icon.png
     - assets/icons/unsaved_icon.png
     - assets/icons/wagl_onbroading.png
     - assets/icons/wagl_onbroading1.png
     - assets/icons/wagl_onbroading2.png
     - assets/icons/leaf_icon.png
     - assets/icons/leafs_icon.png
     - assets/icons/heza_icon.png
     - assets/icons/empty_heza.png
     - assets/icons/heza_blur_icon.png
     - assets/icons/caustion_icon.png
     - assets/icons/true_icon.png
     - assets/icons/false_icon.png
     - assets/icons/setting_icon.png
     - assets/icons/delete_icon_png.png
     - assets/icons/question_icon.png
     - assets/icons/sheild_icon.png
     - assets/icons/hand_icon.png
     - assets/icons/msg_icon.png
     - assets/icons/info_icon.png
     - assets/icons/user_icon.png
     - assets/icons/right_arrow_icon.png
     - assets/icons/lock_icon.png
     - assets/icons/wagl_loading_icon.png
     - assets/icons/refresh_icon.png
     - assets/icons/camera_icon.png
     - assets/icons/gallary_icon.png
     - assets/icons/help_icon.png
     - assets/icons/close_icon.png
     - assets/icons/publish_icon.png
     - assets/icons/delete_icon.png
     - assets/icons/edit_icon_logo.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
        - asset: fonts/Gilroy-Medium.ttf
        - asset: fonts/Gilroy-Bold.ttf
          weight: 600

    - family: Gilroy-Bold
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
          weight: 900

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
